# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jordi < Formula
  desc "Terminal based gRPC client"
  homepage "https://github.com/rnesytov/jordi/"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rnesytov/jordi/releases/download/v0.0.5/jordi_0.0.5_darwin_arm64.tar.gz"
      sha256 "eab7d16c22a08c82f150a1980e764e0172c9a83ad37f0df7b5acc5113a25b2b8"

      def install
        bin.install "jordi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rnesytov/jordi/releases/download/v0.0.5/jordi_0.0.5_darwin_amd64.tar.gz"
      sha256 "da06f1ebc4bb762cc6f828f45da522d1e508184517a47f4432386e9ef0f48b11"

      def install
        bin.install "jordi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rnesytov/jordi/releases/download/v0.0.5/jordi_0.0.5_linux_arm64.tar.gz"
      sha256 "92b0bfc14afb9395f4b85fe539768ae3a50dab8dd2dc32fb8de85fb6350a59c4"

      def install
        bin.install "jordi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rnesytov/jordi/releases/download/v0.0.5/jordi_0.0.5_linux_amd64.tar.gz"
      sha256 "5ba000ac677f8674af058563ad28635b4a709a9d517268bf3f8c23ccfffaa12a"

      def install
        bin.install "jordi"
      end
    end
  end
end
