# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jordi < Formula
  desc "Terminal based gRPC client"
  homepage "https://github.com/rnesytov/jordi/"
  version "0.0.1"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rnesytov/jordi/releases/download/v0.0.1/jordi_0.0.1_osx_arm64.tar.gz"
      sha256 "87add4f1c0a515fe2c7e5d9d13a1a2fd0110944ec3fe5dba8ffa0a8a354542aa"

      def install
        bin.install "jordi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rnesytov/jordi/releases/download/v0.0.1/jordi_0.0.1_osx_x86_64.tar.gz"
      sha256 "91b44f9f364354843d93e00ce2f6ca028143a34de08777d660f2360e20d798e7"

      def install
        bin.install "jordi"
      end
    end
  end
end
